### ISSUE TITLE
MySQL defaults-file location(s)

### ISSUE THREAD

**Issue by StafDehat** [rackerlabs/recap#81]
Per discussion here:
https://github.com/rackerlabs/recap/pull/78#discussion_r104782292

We should decide whether we're going to use 1x my.cnf defaults-file, or if we're going to attempt to read multiple configs (and subsequently, potentially report on multiple SQL instances).

**Comment by StafDehat** [comment]
Relates to this too: https://github.com/rackerlabs/recap/pull/78#discussion_r104780600

**Comment by tonyskapunk** [comment]
From the PR #78 

These are the options:

1. No support to multiple mysql configs - We will drop that support and stick to defaults
1. Support multiple mysql configs.
   A rework is required on the mysql functions some implement the support to multiple configs like `print_mysql`, `print_mysql_procs`, but not for `print_mysql_innodb_status` All these functions are being called from: `run_mysql_report`, either we implement the missing one or move the loop to the calling function.
   1. The supported format is **only** comma separated values, white spaces on names is not supported - This is the easiest solution since is already implemented, low effort
   1. Support comma separated values **and** filenames with white spaces - low-medium effort.

**Comment by StafDehat** [comment]
Honestly, I'd be happy with option 1.  Multiple instances on one box will be a one-off.  If someone needs that functionality, they're welcome to fork and/or PR.

**Comment by tonyskapunk** [comment]
ended up implementing these under #78 commit: 		d1d27cd

**Comment by tonyskapunk** [comment]
Fixed on #78
